# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# copy only project files first
COPY FP.csproj ./
RUN dotnet restore FP.csproj

# copy everything else
COPY . .
RUN dotnet publish FP.csproj -c Release -o /app

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app .
EXPOSE 80
ENTRYPOINT ["dotnet", "FP.dll"]
 
