# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy project file first
COPY FP.csproj ./
RUN dotnet restore FP.csproj

# Copy everything else
COPY . ./
RUN dotnet publish FP.csproj -c Release -o /app

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

# Copy published files
COPY --from=build /app ./

# Create persistent folder for SQLite DB
RUN mkdir -p /data && chmod -R 777 /data

EXPOSE 80
ENTRYPOINT ["dotnet", "FP.dll"]
